services:
  mysql:
    image: mysql:8.0
    env_file: .env
    volumes:
      - ./federated.cnf:/etc/mysql/conf.d/federated.cnf
      - ./mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=$DB_DATABASE"
      - "MYSQL_USER=$DB_USERNAME"
      - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
      - "MYSQL_PASSWORD=$DB_PASSWORD"
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: ["--default-authentication-plugin=mysql_native_password"]

